### PR TITLE
Added script for creating ProductMetadata.plist

### PR DESCRIPTION
**Pull request by Baekalfen**
Hi mkuron,

I work at a print-management company and we have found your code very useful. I couldn't find any license terms, but I hope you are fine with us using it.

I ran into a few problems, when the /Library/Updates/ProductMetadata.plist was empty or non-existing. Therefore, I extended your script a bit to create a new cache. It's tested for printers and works so far without any hiccups. It will most likely also work for other updates.

### CODE REVIEW

**Comment by mkuron** [comment]
Do feel free to use my code for your own purposes. I have just added a LICENSE.txt file to the repository to clarify the license.

It shouldn't be necessary to add a ProductMetadata.plist file. That file automatically gets created when SoftwareUpdate.framework scans for updates. I have not seen any situation where PredicateInstaller failed due to that file missing. If you can describe your situation in more detail, I'll see if I can reproduce it. On a related note, I do have code to populate /Library/Printers/InstalledPrinters.plist in the install_printers.py script. That always seemed to suffice.

**Comment by Baekalfen** [comment]
Thanks for adding such a permissive license, it's much appreciated.

We encountered the problem on a Yosemite test machine with a completely new install. I found the cause to be, that the ProductMetadata.plist file contained just an empty array. Same was encountered once on my MacBook with El Capitan.

I can reproduce it, by moving (or deleting) ProductMetadata.plist, go into the App Store and click the update tab. Wait for it to say "No Updates Available" and confirm the content of the file to be an empty array:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array/>
</plist>
```

Now running this as sudo:
```
/usr/libexec/PlistBuddy -c "Add InstalledPrinters: string MANUFACTURER:HP;MODEL:Officejet Color X555" /Library/Printers/InstalledPrinters.plist
/usr/libexec/PlistBuddy -c "Add Manufacturers: string HP" /Library/Printers/InstalledPrinters.plist
/usr/bin/python predicate_installer.py '"MANUFACTURER:HP;MODEL:Officejet Color X555" in tags'
```

Will give the output:

```
Traceback (most recent call last):
  File "predicate_installer.py", line 62, in <module>
    raise Exception("No products found for %s" % sys.argv[1])
Exception: No products found for "MANUFACTURER:HP;MODEL:Officejet Color X555" in tags
```

**Comment by mkuron** [comment]
Hmm ok, I can reproduce that. However, when I run `softwareupdate --list`, _ProductMetadata.plist_ ist rebuilt and everything works. `softwareupdate --list` is a lot simpler than what your pull request is doing. I haven't yet found a way to update the cache using the framework. I can start a scan, but that doesn't appear to suffice:
```
--- a/predicate_installer.py
+++ b/predicate_installer.py
@@ -43,7 +43,17 @@ if len(sys.argv) < 2:
 predicate = sys.argv[1]
 predicate = NSPredicate.predicateWithFormat_(predicate)
 
+if int(platform.release().split('.')[0]) >= 15: # OS X 10.11 and higher
+       from objc import YES
+       from AppKit import NSBundle
+       bundle = NSBundle.mainBundle()
+       info = bundle.localizedInfoDictionary() or bundle.infoDictionary()
+       info['NSAppTransportSecurity'] = {'NSAllowsArbitraryLoads': YES}
+
 if int(platform.release().split('.')[0]) >= 13: # OS X 10.9 and higher
+       # update cache
+       scan = SUScan.alloc().init()
+       scan.performSynchronousScan()
        
        class ControllerDelegate(NSObject):
                def __getattr__(self, name):
```
I'm pretty sure _SUScan_ is responsible for eventually writing the cache file, so feel free to play around with that `scan.performSynchronousScan()` line and see if you can find a way to make it do that.

**Comment by Baekalfen** [comment]
Ah, didn't know about that side effect. I'm also much more comfortable with ```softwareupdate --list``` than my Python script.

I changed my code to this:
```
--- a/predicate_installer.py
+++ b/predicate_installer.py
@@ -9,6 +9,9 @@ import platform
 from threading import Thread
 from PyObjCTools import AppHelper

+if (not os.path.isfile(metaFile) or os.path.getsize(metaFile) < 2**20): #1KB
+       subprocess.check_call(['/usr/sbin/softwareupdate', "--list"])
+
 finishedInstall = False

 def installlog():
```

I'm going to test it to see if everything works. If it does, then I think I'll go with that.

**Comment by Baekalfen** [comment]
Oops, that's a typo. I meant to write 2**10. If I remember correctly, an empty one could be up to around 300 bytes.

**Comment by mkuron** [comment]
I decided to squash your pull request (2b1700c) because none of the individual commits would have actually worked. It's merged now (b1209f3). Don't forget to
```
git fetch --all
git reset --hard b1209f3
```

**Pull request closed without merging**
